export const actionType =
{
  LAY_DANH_MUC_KHOA_HOC: 'LAY_DANH_MUC_KHOA_HOC',
  LAY_DANH_SACH_KHOA_HOC: 'LAY_DANH_SACH_KHOA_HOC',
  LAY_CHI_TIET_KHOA_HOC:'LAY_CHI_TIET_KHOA_HOC',
  THEM_KHOA_HOC:'THEM_KHOA_HOC',
  UPLOAD_HINH_ANH_KHOAHOC:'UPLOAD_HINH_ANH_KHOAHOC'

} 